//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace words
{
	public class words
	{
		public int count;
		public string word;
		public words (string word, int count)
		{
			this.word = word;
			this.count = count;
		}
	}
}

